services:
  - type: web
    name: repapp
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: REPAPP_DATA_DIR
        value: /tmp/repapp-data
